### ISSUE TITLE
Drop down always shows "No locales in parameters" in Safari

### ISSUE THREAD

**Issue by evgenyt1** [stevensacks/storybook-react-i18next#13]
Under macOS 12.5.1
Safari Version 15.6.1 (17613.3.9.1.16)

Chrome shows drop down correctly

But it starts to show those after activating any other item in menu (may be it just requires redraw).

React 18.2, Storybook 6.5.10, Webpack 5.74.0, nodejs 18.8

https://user-images.githubusercontent.com/1236620/188214653-12472cb8-267e-419e-aa49-a682f57fbc98.mov

**Comment by stevensacks** [comment]
@shilman

**Comment by stevensacks** [comment]
I cannot replicate this locally or on Chromatic in Safari Version 15.6.1 (17613.3.9.1.16).

Have you ruled out the possibility that you have a Safari extension or another Storybook decorate/addon that's causing this?

**Comment by stevensacks** [comment]
Please try Storybook 7 and version 2 of this library.
