### ISSUE TITLE
Any plans to support storybook 7

### ISSUE THREAD

**Issue by juanruben** [stevensacks/storybook-react-i18next#16]
Hi. I am trying to setup the translation select box in storybook 7 beta and it does not display.
Is it possible to be related with the version?

**Comment by jonniebigodes** [comment]
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. Just wanted to follow up on this issue letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Hope you have a great day!

Stay safe

**Comment by meza** [comment]
I've added a pr for this #17

**Comment by stevensacks** [comment]
Storybook 7 is supported in v2.x!
