### ISSUE TITLE
Storybook 7: locale switcher does not open

### ISSUE THREAD

**Issue by lwhiteley** [stevensacks/storybook-react-i18next#19]
Clicking on the locale switcher does not open the dropdown in Storybook 7.

is this still an issue or maybe is there a conflict that is happening. 
All the other custom dropdowns are working, just this one does nothing when clicking

-------

Im using storybook  in an nx setup (shouldnt matter but giving aditional context)

Here are all the plugins im using
```js
 addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-storysource',
    '@storybook/addon-a11y',
    '@storybook/addon-links',
    'storybook-zeplin/register',
    'storybook-dark-mode',
    'addon-screen-reader',
    '@nrwl/react/plugins/storybook',
    'storybook-react-i18next',
  ],
```

versions
```
     "@storybook/addon-a11y": "^7.0.2",
    "@storybook/addon-essentials": "^7.0.2",
    "@storybook/addon-interactions": "^7.0.2",
    "@storybook/addon-links": "^7.0.2",
    "@storybook/addon-storysource": "^7.0.2",
    "@storybook/core-server": "^7.0.2",
    "@storybook/jest": "^0.1.0",
    "@storybook/react": "^7.0.2",
    "@storybook/react-webpack5": "^7.0.2",
    "@storybook/testing-library": "^0.1.0",
    "@storybook/theming": "^7.0.2",
    "addon-screen-reader": "^1.8.6",
    "msw-storybook-addon": "^1.8.0",
    "storybook-dark-mode": "^3.0.0",
    "storybook-react-i18next": "^2.0.1",


    "i18next": "^22.4.14",
    "i18next-browser-languagedetector": "^7.0.1",
    "i18next-http-backend": "^2.2.0",
    "i18next-intervalplural-postprocessor": "^3.0.0",
    "react-i18next": "^12.2.0",
```

system
```bash
 Node : 18.5.0
   OS   : linux x64
   pnpm : 7.30.5
 
Browser:
  - Chrome
  -  Firefox
```

**Comment by stevensacks** [comment]
Have you tried removing all other addons except this one? Did you open the browser console and see any errors or warnings?

It could very well be a conflict with another addons. Perhaps one of those other addons is using old SB6 implementation?

If you clone/fork this repo, you can `yarn start` to launch the storybook example where this is working.

**Comment by lwhiteley** [comment]
ok thanks from looking closer at the example it seems it was my mistake.. i didn't update my preview.js export to be a default export

after doing that then it works.

**Comment by lwhiteley** [comment]
ok now i see as well

the docs on storybook itself has not been reflected.. this is where i got the example

https://storybook.js.org/addons/storybook-react-i18next

**Comment by stevensacks** [comment]
I updated the README here to make it clear to `export default preview`. The official Storybook 7 docs say to do it, but adding it here adds clarity.

Also, I will contact the Storybook team and let them know to update that page. Thanks!
