### ISSUE TITLE
Use with Vite builder

### ISSUE THREAD

**Issue by brettdewoody** [stevensacks/storybook-react-i18next#2]
I'm using Vite (instead of webpack) and when implementing `storybook-react-i18next` there's an error of:

```
Uncaught ReferenceError: require is not defined
    at preview.js?
```

due to this file using a `require` statement. 

Any desire to make this work with Vite? If so I'd like to take a shot at a PR.

**Comment by shilman** [comment]
There are two proposed fixes to a similar problem here:
- https://github.com/storybookjs/storybook/pull/16727/files
- https://github.com/storybookjs/storybook/pull/17108/files

The first renames the file to `.cjs`. The second switches to async imports, which I don't think applies here (including for completeness). That might be enough to solve the issue?

**Comment by MarkLyck** [comment]
@stevensacks @brettdewoody I just stumbled upon this, after running into the same error.

Did you ever find a solution? and if it's not part of this code that needs fixing, which github repo should I be looking at?

I see that 1 of the 2 PRs above was merged, and the other was closed? But at least in the latest storybook it's still broken.

I tried @next, and got this error instead:

```
Uncaught SyntaxError: The requested module '/node_modules/@storybook/addon-docs/node_modules/acorn-jsx/index.js?v=ae9ccf26' does not provide an export named 'default'
```

But that seems unrelated and happens whether storybook-react-i18next is there or not.

**Comment by wanbinkimoon** [comment]
same problem here

**Comment by laneschmidt** [comment]
same issue: https://github.com/stevensacks/storybook-react-i18next/issues/11

[this issue](https://github.com/storybookjs/builder-vite/issues/233) could also be related, i'm pretty ignorant on ES modules vs CommonJS though.

**Comment by dohomi** [comment]
I can confirm, a basic starter with storybook-vite breaks after installing this plugin with the `require` statement. I use React 17 not 18 as mentioned in #11

**Comment by stevensacks** [comment]
Storybook 7 and version 2 of this add-on should work with Vite.
