### ISSUE TITLE
Locale is changed after the story rendered -> `play` function unusable

### ISSUE THREAD

**Issue by bolbovic** [stevensacks/storybook-react-i18next#20]
Some of my stories are using the play function but the problem is that it seems that the locale are changing in every story: I am seeing this `i18next: languageChanged ja` for every stories I go on.
What happens is:
- story renders
- play function plays
- language change
=> story re-renders and break the changes made by the play function

First, I was thinking that the play function was stopped by the language change but I added some waiting time at the end of the play function and the interesting thing is that the language change happens after the play function has ended, not during it. 

Shouldn't the language not change at all when it's not passed in param and such not trigger the language change? Is there any way I can fix this?

I also wanted to try to add `parameter: { locale: "en" },` (default language is `ja`) to the story and in this case, the rendering is even weirder.
- story renders (`ja`)
- play function plays
- language change to `ja` ??
- story renders
- language change to `en`
- story renders

Ideal outcome should be:
- language change to `en`
- story renders
- play function plays

Is it possible to manage that?

**Comment by stevensacks** [comment]
Thanks for reporting this. I will take a look.

**Comment by stevensacks** [comment]
@bolbovic I believe we fixed this in https://github.com/stevensacks/storybook-react-i18next/releases/tag/v2.0.3

Please update and let me know!
