### ISSUE TITLE
Storybook view breaks when using version 2.0.4

### ISSUE THREAD

**Issue by simonabalanbyx** [stevensacks/storybook-react-i18next#22]
Hello, I get the following error when I click on a component in storybook

![Screenshot 2023-06-07 at 14 33 08](https://github.com/stevensacks/storybook-react-i18next/assets/127743377/00759678-0735-4f39-925b-42d5292442e4)

I checked the app with other versions and it seems to work as expected for all versions beyond 2.0.4.

**Comment by Atralbus** [comment]
@stevensacks @Zurdge 

I get the same error on v2.0.4. It works fine with v2.0.2.

**Comment by stevensacks** [comment]
I see the issue. I’ll fix it shortly.

**Comment by stevensacks** [comment]
@Atralbus should be fixed in [v2.0.5](https://github.com/stevensacks/storybook-react-i18next/releases/tag/v2.0.5). I'll close the issue for now and you can reopen it if there's still a problem.

**Comment by Atralbus** [comment]
It's working, thank you very much.
