### ISSUE TITLE
Cannot change language from component

### ISSUE THREAD

**Issue by lgaspari** [stevensacks/storybook-react-i18next#26]
Hey there,

I was wondering if it's also possible to change languages using the function `i18n.changeLanguage()` from a component and not just from Storybook's toolbar as explained in the [tutorial](https://storybook.js.org/addons/storybook-react-i18next).

Here's a reproduction video where I'd like to change languages using my `LanguagePicker` component, however, it doesn't do anything and only updates if I change Storybook's locale.

https://github.com/stevensacks/storybook-react-i18next/assets/20128985/a8a7fa89-3849-4ea8-8c37-fb0b4d8f56ab

**Comment by stevensacks** [comment]
Unfortunately, I don’t believe this is currently possible.

**Comment by stevensacks** [comment]
Your components are running inside an iframe. The i18n provider that they are rendered inside of is a decorator, which is not connected to Storybook outside of the URL params (which SB passes to the iframe as “globals”).

There _might_ be a way to create events which could be dispatched across the barrier, but I’m not sure. I’ll investigate when I update the addon for Storybook 8 and let you know.
