### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by dgateles** [stevensacks/storybook-react-i18next#28]
After following the steps to install, when run storybook `yarn run storybook` i get `ReferenceError: require is not defined` probably by the configurtation on line 13 of `i18next.ts`

**Comment by stevensacks** [comment]
The i18next.ts in the README file is provided only as an example. 

You should use the same configuration that you use in your project. For example, I import my i18n configuration from the src folder into the `.storybook/i18next.ts` file.

If you're having issues with your configuration, please check the [official i18next configuration documentation](https://www.i18next.com/overview/configuration-options).
