### ISSUE TITLE
Strongly type i18next.ts file example

### ISSUE THREAD

**Issue by IonasNeonakis** [stevensacks/storybook-react-i18next#30]
The i18next.ts file in the readme contains variables typed as `any`

It would be nice to have a more strongly typed version of this file

What do you think ? 

I'm willing to make the PR if needed

**Comment by stevensacks** [comment]
This Storybook addon is not a substitute for reading the i18next docs. Technically speaking, the example setup I provide in the README is covered here: https://www.i18next.com/overview/configuration-options

`i18n.init()` param has a type and if you pass it something that violates the type, you'll know.

The instructions for adding a file directly in the `.storybook` folder are only there for the most basic setup as an example. In a real project, you would likely import your i18n settings from the project code itself.

For example:
```ts
import {initReactI18next} from 'react-i18next';
import i18next from 'i18next';
import i18n from '~/i18n'; // the path to your project configuration

i18next.use(initReactI18next).init({
  ...i18n,
  lng: 'en', // you can override your project configuration settings if you need to
  ns: ['common'],
});

export default i18next;
```
