### ISSUE TITLE
Upgrade react-i18next peer dependency to support 15.0.0

### ISSUE THREAD

**Issue by mparisot-antescofo** [stevensacks/storybook-react-i18next#31]
Hello,

react i18next released a v15 last week and therefore this plugin is preventing upgrades as it checks for versions <= 14.

The changelog of the update: https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md

It doesn't look like anything should break on your side but I'll let you evaluate that more properly.

For now I bypassed the issue by adding an override in my package.json and everything is working as expected:

```
  "overrides": {
    "storybook-react-i18next": {
      "react-i18next": "15.0.0"
    }
  }
```

**Comment by stevensacks** [comment]
On it

**Comment by stevensacks** [comment]
https://github.com/stevensacks/storybook-react-i18next/releases/tag/v3.1.3
