### ISSUE TITLE
React 19 compatibility

### ISSUE THREAD

**Issue by gynekolog** [stevensacks/storybook-react-i18next#32]
Hello. The usage of storybook-react-i18next with react 19 causes error `A React Element from an older version of React was rendered. This is not supported.`

![image](https://github.com/user-attachments/assets/cb342909-50ca-4b8b-83ea-93ac83ae356b)

**Comment by stevensacks** [comment]
I'll get to it soon.

**Comment by stevensacks** [comment]
This release (hopefully) solves the issue. Let me know!
https://github.com/stevensacks/storybook-react-i18next/releases/tag/v3.1.8

**Comment by gynekolog** [comment]
@stevensacks It works, thank you for the quick fix and letting me know 🙏
