### ISSUE TITLE
Addon button is not available on docs pages

### ISSUE THREAD

**Issue by jbarreiros** [stevensacks/storybook-react-i18next#4]
Hi, thank you for this storybook addon. It was really easy to get set up.

Is there a way to show the locale button on docs pages? I can only get it to appear on the canvas page.

Canvas page:
![Selection_1206](https://user-images.githubusercontent.com/1109194/147879973-50d3d823-79e1-4f2a-841a-be5cc73b99dc.png)

Docs page:
![Selection_1207](https://user-images.githubusercontent.com/1109194/147879813-345e57a0-62b8-422b-8b22-d3690a9bce7f.png)

I'm using the latest version of storybook-react-i18next, v1.0.15, on Storybook 6.3.7. Also tested on 6.4.9.

Thank you.

**Comment by stevensacks** [comment]
I've asked the Storybook team how to do this and they said it's possible. They're going to send me instructions in a bit and I'll make the required update.

**Comment by stevensacks** [comment]
This has been fixed in release 1.0.16.

**Comment by jbarreiros** [comment]
Hi @stevensacks, thank you for the quick response. I upgraded to v1.0.16, but unfortunately, the button is not showing up on the "Docs" page.

I peaked at the [commit](https://github.com/stevensacks/storybook-react-i18next/commit/06f96416c6f58a7f618bebfe060ada284a7b17a5) and noticed that it only bumped dependencies. No code changes. Was that intentional?

**Comment by stevensacks** [comment]
That’s odd, it’s showing up for me. Try uninstalling and reinstalling.

This addon isn’t the tool, it implements the tool.

https://github.com/stevensacks/storybook-i18n

**Comment by jbarreiros** [comment]
Apologies. You are correct. Spun up a sample project and the button shows up. Something must be funky with my team's storybook setup.

**Comment by stevensacks** [comment]
It might be stuck on the old version. Maybe `rm -rf node_modules` and run install again.
