### ISSUE TITLE
Update Readme.md with examples in .tsx and .mdx files

### ISSUE THREAD

**Issue by Linx-Guiwunsch** [stevensacks/storybook-react-i18next#7]
Could you update Readme.md with code examples showing how to use translations in .tsx and .mdx files?

Thanks.

**Comment by stevensacks** [comment]
This addon empowers you to use your already existing react-i18next setup in your project inside of storybook.

You’ll need to read the react-i18next documentation for instructions on how to use it.

https://react.i18next.com/
